// 2026-10-08: reviewed phone photos. No pupil images or names are published.
const tile={floorColor:'#b6b7aa',floorMaterial:'staff_floor',desktopColor:'#cbb58f',reviewedAt:'2026-10-08',perforatedLectern:true};
const first={...tile,chairs:['#a16d38'],locker:'green-white-checker',lockerRows:2,windowFrame:'#343f34',blindColor:'#c5d0ab',shelfColor:'#e0e3d8',shelf:'books',clockColor:'#36463b',clockSide:'window',extras:['corridor-white-cabinet','perforated-lectern']};
export const OCT8_CLASSROOM_OBSERVATIONS={
 '2F_2-6':{...tile,count:10,revision:'47fbdadb-bae3-440a-9366-082267823914',theme:'연두 의자와 블록 작품 전시',board:'green',back:'tiny-collage-blocks',locker:'green-row',chairs:['#9cae40'],purifier:'front-white',shelf:'books',clockSide:'corridor',extras:['rear-block-display','corridor-art-cards','perforated-lectern'],features:['연두색 의자와 간격을 둔 밝은 책상','넓은 초록 칠판','뒤 게시판의 작은 활동 작품 여러 줄','연두 가운데 줄 목재 사물함','사물함 위 색색 블록 작품','복도 목재 책장과 위쪽 작품 전시','붉은 외창틀·흰 블라인드·밝은 타일']},
 '1F_1-5':{...first,count:10,revision:'76fd8c23-f894-42b1-9852-ee97741c78cb',theme:'연두 흰 사물함과 작품 나무',board:'green',back:'tree-and-timetable',purifier:'rear-white',features:['갈색 의자와 목재색 책상','초록 칠판과 옆 학급 안내판','흰색·연두색 두 줄 사물함','뒤 작품 나무와 가운데 파란 일정판','복도 흰 수납장과 낮은 책장','검정 외창틀과 연녹색 롤블라인드','밝은 큰 사각 타일 바닥']},
 '1F_1-4':{...first,count:8,revision:'52db1170-cca1-4cb3-b5f0-31997102ad81',theme:'사방치기와 꽃 가랜드',board:'green',back:'flower-garlands',purifier:'rear-white',blindColor:'#ded7b9',clockColor:'#a18b61',extras:[...first.extras,'floor-hopscotch','rear-block-display'],features:['갈색 의자와 목재색 책상','초록 칠판 가운데 작은 흰 안내지','뒤 게시판 위 색색 가랜드','흰색·연두색 두 줄 사물함','바닥 앞쪽 사방치기 테이프','목재색 창가 기둥과 밝은 블라인드','복도 흰 수납장과 책이 많은 책장']},
 '1F_1-6':{...first,count:10,revision:'c6d5b0c1-2e9e-4d73-b3fb-87c6a671a55e',theme:'큰 흰 칠판과 꽃 활동지',board:'white-full',back:'flower-activity-strips',purifier:'rear-blue',blindColor:'#d7ddc8',features:['전면 목재 틀의 넓은 흰 칠판','갈색 의자와 일부 회색 방석','흰색·연두색 두 줄 사물함','뒤 게시판의 꽃과 가로로 긴 활동지 줄','복도 흰 수납장과 좁은 목재 책장','검정 외창틀과 밝은 블라인드','뒤 창가 청백색 공기청정기와 타일 바닥']},
 '2F_1-1':{...tile,count:9,revision:'8e2f3c4c-ad5c-4f14-9e7a-583d80a6c284',theme:'열매 작품과 창가 책장',board:'green',back:'fruit-gallery',locker:'green-row',chairs:['#a87948'],purifier:'rear-white',shelf:'yellow',clockSide:'corridor',clockColor:'#a16b4c',extras:['window-bookcase','rear-block-display','perforated-lectern'],features:['갈색 의자와 밝은 목재 책상','초록 칠판과 다양한 안내 카드','연두 중간 줄 목재 사물함','뒤쪽 둥근 열매 작품과 오른쪽 나무 장식','흰 복도 책장과 정리 바구니','붉은 외창틀·크림색 블라인드','앞쪽 금속 강연대와 밝은 타일']},
 '3F_4-7':{...tile,count:9,revision:'bc18f3aa-9cf9-4c28-8f33-c7a3781fc6de',theme:'꽃 콜라주와 창가 복합기',board:'white-wide',back:'flowers-and-ink',locker:'checker',chairs:['#263a4b','#98b346'],chairEvery:7,purifier:'front-blue',shelf:'yellow',clockSide:'corridor',clockColor:'#c1cac0',extras:['rear-cupboard','rear-window-printer','perforated-lectern'],features:['남색 중심 의자에 일부 연두 의자','가운데 넓은 흰 보드','목재·아이보리 번갈아 사물함','뒤 게시판 왼쪽 꽃 작품과 오른쪽 흑백 활동지','앞쪽 청백색 공기청정기','뒤 창가 복합기와 낮은 수납장','복도 책장 위 교구통과 밝은 벽시계']},
 '3F_4-8':{...tile,count:8,revision:'faf68b7f-da8d-4f40-8b26-9ee563428bea',theme:'검정 작품판과 빨간 하트',board:'white-wide',back:'black-panels-heart',locker:'checker',chairs:['#263d50','#9aaf4f'],chairEvery:11,purifier:'rear-white',shelf:'yellow',clockSide:'corridor',clockColor:'#865544',extras:['rear-heart','corridor-art-cards','perforated-lectern'],features:['남색 중심 의자와 밝은 책상','가운데 흰 칠판','목재·아이보리 사물함','뒤 게시판의 흰 콜라주와 검정 사각 작품 격자','뒤 창가 빨간 하트 장식','복도 개방형 교구 책장과 노랑·연두 정리함','붉은 창틀과 흰 블라인드'],uncertainty:'촬영 당시 책상 위에 뒤집힌 의자는 정상 수업 상태로 바닥에 배치함'},
};
