// Photo observations, not generic identity themes. Original photographs remain
// in the photo repository; no people, pupil names or documents are published.
import {ADDITIONAL_CLASSROOM_OBSERVATIONS} from './추가교실사진관찰.mjs';
const observations={
  ...ADDITIONAL_CLASSROOM_OBSERVATIONS,
  '3F_5-3':{count:9,revision:'2026-09-30-012cbaf4',theme:'흰 활동지와 연두 의자',board:'white-narrow',back:'white-papers',locker:'green-row',chairs:['#a6bd45','#ad8759','#293e52'],chairEvery:4,desktopColor:'#d9dcd0',purifier:'rear-blue',shelf:'papers',extras:['back-window-wood','color-bins','lectern'],features:['연두 의자와 일부 목재·남색 의자','초록 칠판 가운데 오른쪽의 좁은 흰 보드','하늘·잔디 배경의 두 줄 흰 활동지','목재 사물함의 연두 중간 줄','뒤 창가 청백색 공기청정기와 높이가 다른 목재 수납장','흰 블라인드와 밝은 마루']},
  '3F_5-6':{count:9,revision:'2026-09-30-3de4fa17',theme:'해바라기 작품과 짝 책상',board:'green',back:'sunflower-autumn',locker:'ivory-row',chairs:['#a6bd45','#ad8759','#293e52'],chairEvery:4,desktopColor:'#d9dcd0',pairedDesks:true,purifier:'front-blue',purifierPosition:[.45,-2.75],shelf:'games',clockSide:'corridor',extras:['back-window-cream','slim-cabinet','window-rect-mirror','autumn-posters','rear-color-bins','window-low-white'],features:['연두색 위주의 혼합 의자와 두 개씩 붙인 책상','흰 보드 없는 초록 칠판','해바라기 두 줄·가을 그림·아래 흰 작품의 뒤 게시판','목재 사물함의 아이보리 중간 줄','앞쪽 청백색 공기청정기','복도 책장의 보드게임·책과 창가 세로 거울','뒤 창가 크림색 키큰 수납장']},
  '4F_4-1':{count:6,revision:'a36aed4a-34c8-4c78-b243-b66074d179cc',theme:'주황 작품과 동그란 창가 전시',board:'green',back:'orange-art',locker:'green-row',chairs:['#263c51','#a4b746'],chairEvery:9,purifier:'rear-blue',shelf:'papers',cabinetColor:'#b9a6ad',extras:['rear-cupboard','corridor-globes','yellow-schedule','lectern'],features:['남색 의자에 소수 연두 의자','뒤 게시판 두 줄 주황 작품과 가운데 큰 공동작품','연두 중간 줄 사물함','복도창의 동그란 작품과 노란 장식','활동지가 쌓인 목재 책장','칠판 오른쪽 노란 일정표']},
  '4F_4-2':{count:6,revision:'74a75f6a-f8a5-468c-8f3e-11a1bafb34a5',theme:'나비 창문과 작품 전시',board:'green',back:'butterfly-art',locker:'checker',chairs:['#293d51','#a3b544'],chairEvery:10,purifier:'rear-blue',shelf:'yellow',extras:['window-butterflies','window-bookcase','slim-cabinet','hoop'],features:['아이보리·목재색 뒤 사물함','창문에 붙인 나비 모양 작품','창가 낮은 책장과 좁은 목재 수납장','뒤 게시판의 두 줄 작은 작품','복도 책장 노란 바구니','뒤 벽 훌라후프']},
  '4F_6-1':{count:5,revision:'9a244be9-eb80-4880-b17a-ca819906ed83',theme:'깃발 가랜드와 분리 사물함',board:'green',back:'bunting-papers',locker:'split',chairs:['#293d51'],purifier:'rear-white',shelf:'blue',extras:['rear-cupboard','slim-cabinet','presentation-stand'],features:['뒤 사물함 사이 크게 비어 있는 공간','연두색 중간 줄 분리 사물함','삼각 깃발 가랜드와 두 줄 활동지','남색 의자','복도 책장 파란 바구니','복도쪽 검정 발표용 보드']},
  '4F_6-2':{count:6,revision:'f26fb7f9-c5cc-4176-9b6f-5dbffb4f6a3a',theme:'검정 작품과 타원 거울',board:'green',back:'dark-art',locker:'checker',chairs:['#293b50'],purifier:'rear-blue',shelf:'books',extras:['oval-mirror','clothes-rack','slim-cabinet','paper-rack'],features:['남색 의자와 밝은 책상','아이보리·목재색 뒤 사물함','검정 바탕 작품을 흰 종이에 붙인 뒤 게시판','복도 기둥의 타원형 거울','창가 금속 옷걸이','뒤쪽 종이 정리대와 청백색 공기청정기']},
  '4F_6-5':{count:6,revision:'b6c19513-b642-4e77-8ab0-162d2a72609a',theme:'목재 의자와 색면 작품',board:'green',back:'gradient-art',locker:'ivory',chairs:['#a47d4f'],purifier:'rear-blue',shelf:'books',extras:['tall-front-cabinet','clothes-rack','locker-stickers','corridor-banner','paper-rack'],features:['목재색 의자','색면·풍경 형태의 세로 작품 게시판','작은 꾸밈이 붙은 아이보리 사물함','앞 창가의 키 큰 회색 수납장','복도창 위 긴 종이 띠','창가 옷걸이와 목재 수납장']},
  '4F_6-7':{count:6,revision:'2fa6e276-d33c-42bb-9729-a15fb736d463',theme:'큰 흰 칠판과 꽃 콜라주',board:'white-wide',back:'flower-collage',locker:'split-checker',chairs:['#9f764b'],purifier:'rear-blue',shelf:'books',extras:['sink','round-mirror','slim-cabinet','lectern'],features:['칠판 중앙의 큰 흰 보드','목재색 의자','뒤 게시판 오른쪽 알록달록 꽃 콜라주','중간 틈이 있는 아이보리·목재색 사물함','창가 뒤쪽 싱크대','복도 기둥 둥근 거울과 갈색 시계']},
  '4F_2-2':{count:6,revision:'3206edbe-d30d-44ce-b78c-77e6f56ac502',theme:'해바라기와 초록 사물함',board:'green',back:'sunflower-tree',locker:'green-double',chairs:['#25394d'],purifier:'front-white',shelf:'yellow',extras:['corridor-mirror'],features:['남색 의자와 밝은 타일 바닥','빨간 외부 창틀과 흰 롤블라인드','살구색 문과 흰 복도 창틀','가운데 연두색 두 줄 사물함','해바라기·나무 배경의 그림 게시판','복도 책장 위 노란 바구니와 세로 거울']},
  '4F_2-3':{count:6,revision:'315ebe32-b08d-45a5-8f25-93a655716254',theme:'노란 작품판과 독서 책장',board:'green',back:'yellow-clipboards',locker:'checker',chairs:['#25394d'],purifier:'front-white',shelf:'orange-books',extras:['clipboards','corridor-clock'],features:['남색 의자와 밝은 타일 바닥','아이보리·목재색 사물함','노란 바탕의 작품과 아래쪽 클립보드 줄','오른쪽 나무 그림 뒤 게시판','복도 쪽 주황 목재 독서 책장','빨간 창틀·흰 롤블라인드와 살구색 문']},
  '1F_3-1':{count:6,revision:'5bbf383b-1d9d-4528-857a-cd8c3eb07f3b',theme:'꽃 작품과 연두 사물함',board:'green',back:'flower-rings',locker:'green-row',chairs:['#26374c','#95ac47'],chairEvery:5,purifier:'front-white',shelf:'wood',extras:['sink','rear-cupboard'],features:['전면 초록 칠판','남색 의자와 일부 연두 의자','연두색 가운데 줄 사물함','꽃 작품과 원형 활동지 뒤 게시판','창가 뒤 싱크대','목재 복도 책장']},
  '1F_3-2':{count:6,revision:'16048786-e17e-428d-81f4-3625adb04d89',theme:'해바라기와 두 줄 그림',board:'green',back:'picture-frames',locker:'green-row',chairs:['#26394d'],purifier:'rear-blue',shelf:'wood',extras:['sunflowers','rear-cupboard','paper-rack'],features:['남색 의자','초록 칠판과 양쪽 학급 안내판','뒤 게시판의 두 줄 그림 액자','연두색 가운데 줄 사물함','창가 기둥 해바라기 장식','뒤쪽 청백색 공기청정기']},
  '1F_3-3':{count:9,revision:'65d4196d-09c1-4dbe-bb68-87efba540102',theme:'티셔츠 작품과 보라 가림천',board:'white-center',back:'shirt-lines',locker:'green-row',chairs:['#253b51','#a3bb48'],chairEvery:5,purifier:'front-blue',shelf:'purple',extras:['color-bins','rear-cupboard'],features:['초록 칠판 가운데 좁은 흰 보드','뒤 게시판의 티셔츠 모양 두 줄 작품','보라색 별빛 가림천','남색과 연두색 의자','앞쪽 청백색 공기청정기','빨강·검정·연두 분리수거함']},
  '3F_5-1':{count:6,revision:'eda5467f-4998-4710-acc4-9248f982979c',theme:'지도 작품과 연두 사물함',board:'green',back:'map-art',locker:'green-row',chairs:['#293e50','#9caf45','#9a7249'],chairEvery:2,purifier:'rear-blue',shelf:'wood',extras:['tall-front-cabinet'],features:['긴 초록 칠판','남색·연두·목재색 의자 혼합','지도와 글자 작품이 있는 뒤 게시판','연두 중간 줄 사물함','전면 키 큰 회색 수납장','복도쪽 낮은 목재 책장'],ownerCorrections:['창가 흰 사각형 이동 보드 삭제'],uncertainty:'사진 사이 뒤 수납장 구성이 달라 후반 사진의 연두 중간 줄을 우선 반영'},
  '3F_5-2':{count:6,revision:'d765a2d0-53bc-4f1e-8247-c32337146bfb',theme:'검정 작품 격자와 색종이',board:'green',back:'black-grid',locker:'checker',chairs:['#294052','#a77d4c','#9aaf40'],chairEvery:2,purifier:'rear-blue',shelf:'yellow',extras:['rear-tall-cabinet','lectern'],features:['뒤 게시판의 검정 작품·노랑/분홍 배경 격자','아이보리·목재색 사물함','남색·갈색·일부 연두색 의자','창가 뒤 키 큰 수납장','금속 이동 강연대','복도 책장 위 노란 바구니']},
};
export const UPLOADED_CLASSROOM_PROFILES=Object.fromEntries(Object.entries(observations).map(([roomId,o])=>[roomId,{
  ...o,roomId,referenceRoom:roomId.startsWith('4F_2-')?'4F_2-1':'4F_6-4',photoStatus:'reviewed',photoCount:o.count,sourceRevision:o.revision,
  reviewedAt:ADDITIONAL_CLASSROOM_OBSERVATIONS[roomId]?'2026-10-02':'2026-09-30',observedFeatures:o.features,lowerWall:'#b8c3b4',accent:'#a4b29b',trayColor:'#d8c254',boardLayout:0,lockerPattern:0,
  seatCountIsApproximate:true,layoutIsApproximate:true,
}]));
