// Approved phone photographs reviewed 2026-10-02. Counts are source photos;
// furniture counts/dimensions are approximate. No pupil identity is reproduced.
export const ADDITIONAL_CLASSROOM_OBSERVATIONS={
 '4F_4-4':{count:9,revision:'1065e061-b691-4b51-82ac-9f41cab5a291',reviewedAt:'2026-10-07',theme:'나뭇잎 작품과 노란 바구니 책장',board:'white-wide',back:'leaf-worksheets',locker:'green-row',chairs:['#263b50','#a5bd43'],chairEvery:9,desktopColor:'#d4c3a3',floorColor:'#b7b4a3',floorMaterial:'staff_floor',purifier:'rear-blue',shelf:'yellow',clockSide:'corridor',clockPosition:3.65,clockColor:'#895e4d',extras:['rear-cupboard','corridor-slim-cabinet','perforated-lectern'],features:['남색 의자 위주에 소수 연두색 의자와 밝은 목재 책상','초록 칠판 가운데 넓은 흰 보드','뒤 게시판 왼쪽 콜라주·가운데 나뭇잎 작품·오른쪽 흰 활동지 세 구역','목재 사물함의 연두색 가운데 줄','복도 아래 목재 책장과 노란 바구니','복도 기둥의 갈색 원형 시계와 좁은 목재장','붉은 외창틀과 높이가 다른 흰 롤블라인드','회베이지 사각 타일 바닥과 청백색 공기청정기','앞쪽 은색 이동 강연대와 천장 보호망 선풍기'],uncertainty:'좌석 수와 가구 치수는 사진 가림 때문에 근사하며 기존 출입문과 통로를 유지함'},
 '3F_5-4':{count:9,revision:'cd26fb3e-ab91-4693-bf64-0a5dbfc0d4bd',theme:'흰 칠판과 오른쪽 작품 모음',board:'white-wide',back:'right-paper-cluster',locker:'ivory-row',chairs:['#a2b946','#ae8c5d','#293d50'],chairEvery:3,desktopColor:'#d5c9ae',purifier:'rear-blue',shelf:'games',clockSide:'window',extras:['rear-tall-cabinet','color-bins','yellow-schedule','corridor-banner'],features:['가운데 넓은 흰 칠판과 왼쪽 노란 일정표','연두·갈색·남색 의자 혼합','아이보리 가운데 줄 사물함','뒤 게시판 오른쪽 종이 작품 묶음','복도 책장에 교구와 게임 상자','창가 기둥 시계와 흰 블라인드','뒤쪽 높은 목재장 위 녹색 정리함'],uncertainty:'마지막 사진 게시물 구성이 달라 앞의 반복 시점 사진을 우선함'},
 '2F_3-5':{count:10,revision:'cb2567f5-1672-48aa-9614-eebb116fabe5',theme:'초록 액자 게시판과 넓은 흰 보드',board:'white-wide',back:'green-framed-grid',locker:'green-row',chairs:['#a2bb48','#283c51'],chairEvery:3,desktopColor:'#d4c5a6',purifier:'rear-blue',shelf:'yellow',extras:['rear-cupboard','window-plant','paper-rack'],features:['가운데 흰 칠판과 양끝 초록판','연두 위주와 남색 의자','연두 중간 줄 사물함','연두 테두리 작품 격자와 오른쪽 달력 게시판','복도 아래 목재 책장과 교구','블라인드를 올린 밝은 외창','창가 작은 화분과 뒤쪽 청백색 공기청정기']},
 '3F_5-5':{count:10,revision:'d068947a-9a0c-4d44-a36b-74cbab7d399e',theme:'물방울 작품과 세 구획 게시판',board:'green',back:'three-part-drops',locker:'checker',chairs:['#a3b94c','#ad895f','#293a4d'],chairEvery:4,desktopColor:'#dedbd0',purifier:'rear-blue',shelf:'wood',extras:['window-rect-mirror','yellow-schedule','corridor-banner'],features:['흰 보드 없는 초록 칠판','연두 의자 위주에 갈색·남색 의자','아이보리·목재색 사물함','왼쪽 흰 작품·가운데 색색 물방울·오른쪽 어두운 작품의 세 구획 게시판','창가 직사각형 거울','목재 복도 책장과 위쪽 게시물','밝은 회백색 책상과 일부 목재 상판']},
 '4F_6-3':{count:6,revision:'0310f6a8-4868-43cf-a0c7-b5bb9eb70216',theme:'신문 콜라주와 흰 칠판',board:'white-wide',back:'news-collage',locker:'checker',chairs:['#b49468','#a3bb55'],chairEvery:7,desktopColor:'#d7cbb1',purifier:'front-blue',shelf:'games',extras:['rear-tall-cabinet','color-bins'],features:['큰 흰 칠판과 목재 교탁','목재 의자 위주에 일부 연두 의자','신문·사진 형태의 다양한 크기 뒤 콜라주','아이보리·목재색 사물함','뒤 복도 쪽 높은 목재 수납장','복도 아래 두 개의 교구·게임 책장','연회색 롤블라인드와 밝은 마루']},
 '3F_4-6':{count:8,revision:'7de1ff2b-31f6-45f2-a07d-aa6f65399fa8',theme:'연두 의자와 창가 교구칸',board:'white-wide',back:'postcard-gallery',locker:'green-row',chairs:['#9fbd43'],desktopColor:'#d6d5bf',purifier:'front-blue',shelf:'yellow',extras:['long-window-cubbies','clothes-rack','rear-cupboard','corridor-globes'],features:['연두색 의자와 밝은 책상','중앙 대형 흰 칠판','뒤 게시판의 큰 색색 그림과 전시물','연두 중간 줄 사물함','창가 긴 개방형 교구 수납칸','복도창 동그란 작품과 노란 바구니','창가 흰 블라인드와 천장 선풍기']},
 '3F_4-5':{count:8,revision:'8aaedb62-ba80-4773-a23e-02023a30c70d',theme:'색면 작품과 남색 의자',board:'green',back:'striped-landscapes',locker:'green-row',chairs:['#26394f','#a5bb4e'],chairEvery:6,desktopColor:'#d7cbb0',purifier:'rear-blue',shelf:'yellow',clockSide:'window',extras:['clothes-rack','rear-cupboard'],features:['흰 보드 없는 넓은 초록 칠판','남색 위주와 일부 연두 의자','뒤 게시판의 작고 선명한 색면 풍경 작품 두 줄','연두 중간 줄 사물함','창가 금속 옷걸이와 벽시계','목재 복도 책장과 노란 바구니','청록빛 복도 유리와 흰 롤블라인드']},
};
